thresholds:
  high: 55
  review: 35
weights:
  SPF_FAIL: 35
  DKIM_FAIL_OR_NODMARC: 25
  FROM_REPLYTO_MISMATCH: 20
  LINK_MISMATCH: 20
  IDN_OR_SUSPICIOUS_TLD: 15
  DISPLAY_NAME_IMPERSONATION: 20
  DANGEROUS_ATTACHMENT: 40
  URGENCY_BAIT: 15
  NEW_DOMAIN_LOCAL: 10
  RETURN_PATH_MISMATCH: 10
  DMARC_ALIGNMENT_FAIL: 25
  THREAD_HIJACK: 30
  MESSAGEID_DOMAIN_MISMATCH: 10
  SHORTENER_OR_REDIRECT: 20
  PORT_PROTOCOL_ODDITY: 25
  BRAND_OFFDOMAIN: 30
  OAUTH_CONSENT_PHISH: 40
  ARC_INVALID: 15
  IMAGE_ONLY_BODY: 25
  QR_CODE_FOUND: 30
  PASSWORD_ARCHIVE: 45
  CAL_INVITE_PHISH: 25
  BANK_CHANGE_REQUEST: 45
  FORM_CRED_HARVEST: 40
  BIMI_EXPECTATION_VIOLATED: 10
  RTL_OVERRIDE_OR_ZW: 25
combos:
- when:
  - BRAND_OFFDOMAIN
  - IDN_OR_SUSPICIOUS_TLD
  bonus: 15
- when:
  - THREAD_HIJACK
  - URGENCY_BAIT
  bonus: 15
- when:
  - OAUTH_CONSENT_PHISH
  - SHORTENER_OR_REDIRECT
  bonus: 10
- when:
  - SPF_FAIL
  - RETURN_PATH_MISMATCH
  bonus: 10
- when:
  - DMARC_ALIGNMENT_FAIL
  - MESSAGEID_DOMAIN_MISMATCH
  bonus: 10
allowlists:
  domains:
  - amtrak.com
  - bananarepublic.com
  - digikey.com
  - equifax.com
  - github.com
  - google.com
  - indeed.com
  - lifetime.life
  - microsoft.com
  - oldnavy.com
  - razer.com
  - samsungcloud.com
  - seatgeek.com
  - substack.com
  - wanderu.com
  senders: []
